CREATE TABLE DEPARTAMENTOS(
    ID_DEPTO        NUMERIC(3,0)
    CONSTRAINT DEPTO_PK PRIMARY KEY,
    NOM_DEPTO       VARCHAR2(50)
    CONSTRAINT DEPTO_NOM_NN NOT NULL
    CONSTRAINT DEPTO_NOM_UK UNIQUE
);

CREATE TABLE CARRERAS(
    ID_CARR         VARCHAR2(10)
    CONSTRAINT CARR_pk PRIMARY KEY,
    NOM_CARRERA     VARCHAR2(50)
    CONSTRAINT CARR_NOM_NN NOT NULL
    CONSTRAINT CARR_NOM_UK UNIQUE,
    ID_DEPTO        NUMERIC(3,0)
    CONSTRAINT CARR_DEPTO_FK REFERENCES 
    DEPARTAMENTOS(ID_DEPTO)
);

CREATE TABLE PABELLONES(
    ID_PAB          NUMERIC(2,0)
    CONSTRAINT PAB_PK PRIMARY KEY,
    NOM_PAB         VARCHAR2(10)
    CONSTRAINT PAB_NOM_NN NOT NULL
    CONSTRAINT PAB_NOM_UK UNIQUE
);

CREATE TABLE AULAS(
    COD_AULA        NUMERIC(4,0)
    CONSTRAINT AULAS_PK PRIMARY KEY,
    NUM_AULA        NUMERIC(3,0)
    CONSTRAINT AULA_NUM_NN NOT NULL,
    ID_PAB          NUMERIC(2,0)
    CONSTRAINT AULA_PAB_FK REFERENCES
    PABELLONES(ID_PAB),
    CONSTRAINT AULAS_NUM_PAB_UK UNIQUE(NUM_AULA,ID_PAB)
);

CREATE TABLE ARDUINOS(
    ID_ARD      NUMERIC(3,0)
    CONSTRAINT ARD_PK PRIMARY KEY,
    COD_AULA    NUMERIC(4,0)
    CONSTRAINT ARD_AULA_FK REFERENCES
    AULAS(COD_AULA)
);

CREATE TABLE ROLES_USER(
    ID_ROL          NUMERIC(2,0)
    CONSTRAINT ROL_PK PRIMARY KEY,
    ROL             VARCHAR2(30)
    CONSTRAINT ROL_ROL_NN NOT NULL
    CONSTRAINT ROL_ROL_UK UNIQUE
);

CREATE TABLE USUARIOS(
    ID_USR          NUMERIC(4,0)
    CONSTRAINT USR_PK PRIMARY KEY,
    USUARIO         VARCHAR2(20)
    CONSTRAINT USR_USR_UK UNIQUE,
    CONTRASENIA     VARCHAR2(20)
    CONSTRAINT USR_PASS_NN NOT NULL,
    ID_ROL          NUMERIC(2,0)
    CONSTRAINT USR_ROL_FK REFERENCES ROLES_USER(ID_ROL)
);

CREATE TABLE USUARIOS_CARRERAS(
    ID_USR      NUMERIC(4,0)
    CONSTRAINT USR_CARR_FK1 REFERENCES
    USUARIOS(ID_USR) ON DELETE CASCADE,
    ID_CARR     VARCHAR2(10)
    CONSTRAINT USR_CARR_FK2 REFERENCES
    CARRERAS(ID_CARR) ON DELETE CASCADE,
    CONSTRAINT USR_CARR_UK UNIQUE(ID_USR,ID_CARR)
);  

CREATE TABLE PERMISOS(
    COD_AULA     NUMERIC(4,0)
    CONSTRAINT PERM_AULA_FK REFERENCES 
    AULAS(COD_AULA) ON DELETE CASCADE,
    ID_ROL       NUMERIC(2,0)
    CONSTRAINT PERM_ROL_FK REFERENCES 
    ROLES_USER(ID_ROL) ON DELETE CASCADE,
    CONSTRAINT PERM_UK UNIQUE(COD_AULA,ID_ROL)
);

CREATE SEQUENCE DEPT_ID_SEQ
INCREMENT BY 1
START WITH 1;

CREATE SEQUENCE USR_ID_SEQ
INCREMENT BY 1
START WITH 1;

CREATE SEQUENCE ARD_ID_SEQ
INCREMENT BY 1
START WITH 1;

CREATE SEQUENCE ROL_ID_SEQ
INCREMENT BY 1
START WITH 1;

CREATE SEQUENCE AULA_ID_SEQ
INCREMENT BY 1
START WITH 1;

/
CREATE OR REPLACE PROCEDURE insertUser(usr in usuarios.usuario%type,
                            pass in usuarios.contrasenia%type,
                            id_rol in usuarios.id_rol%type)                   
IS
BEGIN
    INSERT INTO USUARIOS VALUES(USR_ID_SEQ.NEXTVAL,usr,pass,id_rol);
END insertUser;
/
CREATE OR REPLACE PROCEDURE insertUsrCarr(idUsr IN USUARIOS.ID_USR%type, 
                                          idCarr IN CARRERAS.ID_CARR%type)
IS
BEGIN
    INSERT INTO USUARIOS_CARRERAS VALUES(idUsr,idCarr);
END insertUsrCarr;
/
CREATE OR REPLACE PROCEDURE deleteUsrCarr(idUsr IN USUARIOS.ID_USR%type, 
                                          idCarr IN CARRERAS.ID_CARR%type)
IS
BEGIN
    DELETE FROM USUARIOS_CARRERAS
    WHERE ID_USR = idUsr
    AND ID_CARR LIKE idCarr;
END deleteUsrCarr;
/
CREATE OR REPLACE PROCEDURE insertPerm(codAula IN AULAS.COD_AULA%type,
                                       idRol IN ROLES_USER.ID_ROL%type)
IS
BEGIN
    INSERT INTO PERMISOS VALUES(codAula,idRol);
END insertPerm;
/
CREATE OR REPLACE PROCEDURE deletePerm(codAula IN AULAS.COD_AULA%type,
                                       idRol IN ROLES_USER.ID_ROL%type)
IS
BEGIN
    DELETE FROM PERMISOS WHERE COD_AULA=codAula AND ID_ROL=idRol;
END deletePerm;
/
CREATE OR REPLACE FUNCTION selectOneUsr_User(usr in usuarios.usuario%type) 
RETURN SYS_REFCURSOR
IS
    curUsuarios SYS_REFCURSOR;
BEGIN
    OPEN curUsuarios FOR 
        SELECT U.ID_USR,U.USUARIO,U.CONTRASENIA,RUS.ROL
        FROM USUARIOS U
        JOIN ROLES_USER RUS ON U.ID_ROL = RUS.ID_ROL
        WHERE U.USUARIO = usr;
    RETURN curUsuarios;
END;
/
CREATE OR REPLACE FUNCTION selectOneUsr(id_usrIN in usuarios.id_usr%type) 
RETURN SYS_REFCURSOR
IS
    curUsuarios SYS_REFCURSOR;
BEGIN
    OPEN curUsuarios FOR 
        SELECT U.ID_USR,U.USUARIO,U.CONTRASENIA,RUS.ROL
        FROM USUARIOS U
        JOIN ROLES_USER RUS ON U.ID_ROL = RUS.ID_ROL
        WHERE U.ID_USR = id_usrIN;
    RETURN curUsuarios;
END;
/
CREATE OR REPLACE FUNCTION selectAllUsr RETURN SYS_REFCURSOR
IS
    curUsuarios SYS_REFCURSOR;
BEGIN
    OPEN curUsuarios FOR 
        SELECT U.ID_USR,U.USUARIO,U.CONTRASENIA,RUS.ROL
        FROM USUARIOS U
        JOIN ROLES_USER RUS ON U.ID_ROL = RUS.ID_ROL
        ORDER BY U.ID_USR;
    RETURN curUsuarios;
END;
/
CREATE OR REPLACE FUNCTION getAulas RETURN SYS_REFCURSOR
IS
    aulas SYS_REFCURSOR;
BEGIN
    OPEN aulas FOR
        SELECT A.COD_AULA,A.NUM_AULA,P.NOM_PAB
        FROM AULAS A
        JOIN PABELLONES P ON 
        A.ID_PAB = P.ID_PAB
        ORDER BY A.COD_AULA;
    RETURN aulas;
END;
/
CREATE OR REPLACE FUNCTION getRoles RETURN SYS_REFCURSOR
IS
    roles SYS_REFCURSOR;
BEGIN
    OPEN roles FOR
        SELECT * 
        FROM ROLES_USER
        ORDER BY ID_ROL;
    RETURN roles;
END;
/

INSERT INTO DEPARTAMENTOS VALUES(DEPT_ID_SEQ.NEXTVAL, 
                                 'Departamento de tecnología digital');

INSERT INTO CARRERAS VALUES('C24','Diseno y Desarrollo de Software',1);

INSERT INTO PABELLONES VALUES(1, 'Pabellon A');

INSERT INTO ROLES_USER VALUES(ROL_ID_SEQ.NEXTVAL,'Profesor');
INSERT INTO ROLES_USER VALUES(ROL_ID_SEQ.NEXTVAL,'Estudiante');
INSERT INTO ROLES_USER VALUES(ROL_ID_SEQ.NEXTVAL,'Rector');
INSERT INTO ROLES_USER VALUES(ROL_ID_SEQ.NEXTVAL,'Gerente');
INSERT INTO ROLES_USER VALUES(ROL_ID_SEQ.NEXTVAL,'Administrativo');
INSERT INTO ROLES_USER VALUES(ROL_ID_SEQ.NEXTVAL,'Conserje');

INSERT INTO USUARIOS VALUES(USR_ID_SEQ.NEXTVAL,'juan.condori.p','T3csup9025',2);
INSERT INTO USUARIOS VALUES(USR_ID_SEQ.NEXTVAL,'abel.ponce','T3csup7856',2);
INSERT INTO USUARIOS VALUES(USR_ID_SEQ.NEXTVAL,'brayan.chile','T3csup2590',2);
INSERT INTO USUARIOS VALUES(USR_ID_SEQ.NEXTVAL,'christian.cuarite','T3csup6724',2);
INSERT INTO USUARIOS VALUES(USR_ID_SEQ.NEXTVAL,'leonardo.diaz','T3csup1567',2);
INSERT INTO USUARIOS VALUES(USR_ID_SEQ.NEXTVAL,'maria.cuba','T3csup3578',2);

INSERT INTO AULAS VALUES(AULA_ID_SEQ.NEXTVAL,210,1);

INSERT INTO ARDUINOS VALUES(ARD_ID_SEQ.NEXTVAL, 1);

INSERT INTO USUARIOS_CARRERAS VALUES(1,'C24');
INSERT INTO USUARIOS_CARRERAS VALUES(2,'C24');
INSERT INTO USUARIOS_CARRERAS VALUES(3,'C24');
INSERT INTO USUARIOS_CARRERAS VALUES(4,'C24');
INSERT INTO USUARIOS_CARRERAS VALUES(5,'C24');
INSERT INTO USUARIOS_CARRERAS VALUES(6,'C24');

INSERT INTO PERMISOS VALUES(1,1);
INSERT INTO PERMISOS VALUES(1,2);
INSERT INTO PERMISOS VALUES(1,3);
INSERT INTO PERMISOS VALUES(1,4);
INSERT INTO PERMISOS VALUES(1,5);
